export const blogTypes = {
  GET_USER_BLOG: "GET_USER_BLOG",
  GET_SINGLE_POST: "GET_SINGLE_POST",
  GET_POST_LOADING: "GET_POST_LOADING",
  GET_SINGLE_POST_LOADING: "GET_SINGLE_POST_LOADING",
  CREATE_USER_BLOG: "CREATE_USER_BLOG",
  DELETE_USER_BLOG: "DELETE_USER_BLOG",
  EDIT_USER_BLOG: "EDIT_USER_BLOG",
};
